<?
require 'stranica.php';
$povijest = new Stranica();
$povijest->SetSadrzaj('
<h3>Kratka povijest MKD “Braca Miladinovci” u Osijeku</h3><br>
<p>U prepoznavanju važnosti ocuvanja nacionalnog identiteta, pocetkom devedesetih godina prošlog stoljeca medu skupinom entuzijasta, pripadnika makedonske nacionalne manjine u Osijeku, rodila se ideja o pokretanju aktivnosti koje ce doprinositi razvoju i njegovanju specificnosti njihove kulture i obicaja. Stoga, kao rezultat napora <b>Blagoje Jovanovskog, Jagode Treneske Cveticanin, Jagode Mitanovske Janic, Ljubomira Dojcinova, Srete Nikolovskog, Ljubomira Stamenkovskog, Lazara Jordanova, Mire Trenevskog  i Jelene Sladic</b>, 22. listopada 1994. u Osijeku osniva se Makedonsko kulturno društvo „Braca Miladinovci“. </p>
<p>Društvo nosi ime po braci Konstantina i Dimitrija Miladinov, makedonski pjesnici s kraja 19. stoljeca, o cijem znacaju govori i cinjenica da je njihov rad za života podupirao poznati dakovacki biskup i mecena Josip Juraj Strossmayer, te je upravo uz njegovu podršku 1861.g. omoguceno tiskanje Zbornika „Narodnih pjesama“ brace Miladinov, jedno od najvažnijih djela makedonske jezicke i literarne kulture.</p>
<p>MKD „Braca Miladinovci“ jedno je od ukupno šest društava u okviru Zajednice Makedonaca u Republici Hrvatskoj. Tijekom ovih 15 godina, ovo Društvo svojim programima obogacuje kulturni život našeg grada organizirajuci brojna druženja, koncerte, znanstvene skupove, izložbe, promocije knjiga, projekcije filmova i t.d., koje su omogucene sredstvima Savjeta za nacionalne manjine Vlade Republike Hrvatske, Gradskog poglavarstva Osijeka i Županije Osjecko-baranjske.</p>
<p>U sklopu Društva djeluju sekcije makedonske glazbe i plesa za odrasle i djecu, kulinarska, etno i djecja radionica, i škole za ucenje makedonskoj jezika za odrasle i djecu.</p>
<p>Glazbenu sekciju od samog osnutka vodi prof. Jagoda Treneska Cveticanin, sadašnja predsjednice Društva. U sklopu ove sekcije djeluje pjevacka skupina „<b>Vardarki</b>“ koja izvodi tradicionalne makedonske pjesme, a organiziraju se i koncerti ozbiljne glazbe.</p>
<p>Folklornu skupinu „<b>Tanec</b>” (mladi i stariji) vodili su koreografi Maja Farkaš, Marija Grbavica, Andrija Iža i Sladana Bošnjakovic. Ona njeguje ljubav prema makedonskoj bogatoj folklornoj baštini.</p>
<p>Najmladi ljubitelji makedonske kulture takoder aktivno sudjeluju u radu Društva, u svojoj djecjoj radionici “<b>Bisercinja</b>” pod vodstvom Sanje Buzadžic.</p>
<p>Pod vodstvom Marije Cincurak je <b>kulinarska sekcija</b> koja njeguje i prezentira makedonske kulinarske specijalitete, te etno radionica „<b>Vezilki</b>“ koja se bavi tradicionalnim vezom, izradom nakita, nošnji i dr.</p>
<p>Od 2008. godine pocela s radom i <b>jezicna sekcija</b> za odrasle koja se bavi ucenjem makedonskog jezika, pod vodstvom prof. Blagoje Jovanovskog.</p>
<p>Škola makedonskog jezika i kulture za ucenike osnovnih razreda pocela je 2008. godine podrškom hrvatskog Ministarstva znanosti, obrazovanja i športa kao <b>izborna nastava makedonskog jezika</b> po modelu C. Nastava se odvija svake subote u prostorijama OŠ „Vijenac“ u Osijeku. Nastavu pohada 10 ucenika od 2. do 8. razreda osnovne škole koji se kroz program stjecu znanjem iz makedonskog jezika, povijesti i kulture. Program vodi Julijana Mladenovska Tešija. </p>
<p>Glavne manifestacije MKD „Braca Miladinovci“ su:
<ul><li><b>“Dani Brace Miladinov”</b>, koja se istovremeno održava u Osijeku i Ðakovu zbog stoljetne povezanosti Ðakova i Struge vec 12 godina, i to u lipnju/junu, kada je i tiskan Zbornik brace Miladonov, 1861. godine. Program je bogat kulturnim, umjetnickim i glazbenim sadržajima.</li><br><br>
<li><b>„Dani Makedonske kulture“</b> jedna od najznacajnijih manifestacija našeg Društva. Održava se vec 14 godina u listopadu/oktobru, na rodendan Društva. Rijec je o bogatom višednevnom programu u kojem se poštovatelji makedonske kulture imaju priliku upoznati sa najrazlicitjim kulturnim sadržajima, novim naslovima knjiga makedonskih pisaca, izložbama makedonskih slikara, projekcijom makedonskih filmova, i uživati u makedonskoj glazbi i plesu, ili probati pokoji kulinarski specijalitet iz bogate makedonske kuhinje. Program cesto obogacuju pripadnici drugih manjinskih skupina koji, kao gosti Društva, takoder predstavljaju svoje specificnosti.</li><br><br>
<li>Manifestacija <b>„Makedonska vecer“</b> održava se po 6. puta u ožujku/martu. Posvecena je prazniku “8. mart” i dolasku proljeca, a glavna je tema veceri glazba i zabava sa svim ljubiteljima makedonskog etnosa iz naše Županije i šire.</li>
</ul></p>
<p>Ovakve aktivnosti nas vesele i pokazuju da je suživot razlicitih kultura i obicaja na našem tlu i moguc i neizmjerno važan u razvijanju razumijevanja i tolerancije prema manjinskim skupinama. Za svoj rad i doprinos zajednici, MKD „Braca Miladinovci“ je 1999.g. nagradeno velikim priznanjem <b>„Pecat Grada Osijeka za promicanje multieticnosti i multikulturalnosti“</b>. Društvo je dobitnik je i <b>„Priznanja Grada Struge za njegovanje makedonskog jezika“</b> (2004 god), te <b>„Priznanja Grada Osijeka za najbolji prikaz korizmenih i uskrsnih obicaja“</b> (2007 god), kao i brojnih diploma i zahvalnica</p>
<p>Sadašnje rukovodstvo Društva (UO): Jagoda Cveticanin - predsjednica, Krste Atanasovski  - dopredsjednik, Andrijana Galovic - tajnica, Dragoljub Siljanovski, Julijana Mladenovska Tešija, Sanja Buzadžic i Slobodan Krsteski - clanovi.
Na prijedlog Društva, na lokalnim izborima 2007. god. za pretstavnika Makedonske nacionalne manjine –za Grad Osijek izabrana je Marija Cincurak iz Osijeka, a za Osjecko-baranjsku županiju Dragoljub Siljanoski iz Našica.</p>
<p>Clanovi Društva, Makedonci i prijatelji makedonske kulture, okupljeni  u svojim prostorijama  gotovo svakodnevno u zajednickom druženju rade na osmišljavanju buducih aktivnosti. Njihov rad je volonterski, voden ljubavi  prema izvornoj makedonskoj pjesmi, plesu, makedonskoj poeziji, jeziku ili makedonskoj kuhinji, kao najljepši nacin izražavanja svog nacionalnog identiteta i povezivanja sa svojom drugom domovinom.</p><br><br>
');
$povijest -> Prikaz();
?>